services:
  web:
    build: .
    container_name: generacion_contratos-container
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    networks:
      atalayavps_network:
 
  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - ./.env
    networks:
      atalayavps_network:
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "8082:80"
    networks:
      atalayavps_network:
 
networks:
  atalayavps_network:
    external: true
 
volumes:
  db_data: